name: Build Ubuntu 18.04 Images

on:
  push:
    branches:
      - main
    paths:
      - 'ubuntu-18.04/*'
      - '.github/workflows/build-ubuntu-18.04.yml'
  pull_request:
    paths:
      - 'ubuntu-18.04/*'
      - '.github/workflows/build-ubuntu-18.04.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      alternate-latest-mode: true
      docker-context: "./ubuntu-18.04"
      dockerfile: "./ubuntu-18.04/Dockerfile"
      dockerhub_imagename: "chianetwork/ubuntu-18.04-builder"
      image_subpath: "ubuntu-18.04-builder"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
