name: Build Alpine Image

on:
  push:
    branches:
      - main
    paths:
      - "alpine/*"
      - ".github/workflows/build-alpine.yml"
  pull_request:
    paths:
      - "alpine/*"
      - ".github/workflows/build-alpine.yml"
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * 5"

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      alternate-latest-mode: true
      docker-context: "./alpine"
      dockerfile: "./alpine/Dockerfile"
      dockerhub_imagename: "chianetwork/alpine-builder"
      image_subpath: "alpine-builder"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
