name: Build Aptly Image

on:
  push:
    branches:
      - main
    paths:
      - 'aptly/*'
      - '.github/workflows/build-aptly.yml'
  pull_request:
    paths:
      - 'aptly/*'
      - '.github/workflows/build-aptly.yml'
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    uses: Chia-Network/actions/.github/workflows/docker-build.yaml@main
    with:
      docker-context: "./aptly"
      dockerfile: "./aptly/Dockerfile"
      dockerhub_imagename: "chianetwork/aptly"
      image_subpath: "aptly"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}
